<?xml version="1.0" encoding="utf-8"?><Database Name="WebMenuOrder" Class="dbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Account" Member="Accounts">
    <Type Name="Account">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IdTypeAccount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DisplayName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="Account_Bill" Member="Bills" ThisKey="Id" OtherKey="IdAccount" Type="Bill" />
      <Association Name="Account_Staff" Member="Staffs" ThisKey="Id" OtherKey="IdAccount" Type="Staff" />
      <Association Name="TypeAccount_Account" Member="TypeAccount" ThisKey="IdTypeAccount" OtherKey="IdAccount" Type="TypeAccount" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TypeAccount" Member="TypeAccounts">
    <Type Name="TypeAccount">
      <Column Name="IdAccount" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TypeAccount" Member="TypeAccount1" Type="System.String" DbType="NVarChar(125) NOT NULL" CanBeNull="false" />
      <Association Name="TypeAccount_Account" Member="Accounts" ThisKey="IdAccount" OtherKey="IdTypeAccount" Type="Account" />
    </Type>
  </Table>
  <Table Name="dbo.Bill" Member="Bills">
    <Type Name="Bill">
      <Column Name="IdBill" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdAccount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TimeCome" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TimeOut" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IdTable" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Discount" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PaymentMethod" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TotalMoney" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IdStaff" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Bill_DetailBill" Member="DetailBills" ThisKey="IdBill" OtherKey="IdBill" Type="DetailBill" />
      <Association Name="Account_Bill" Member="Account" ThisKey="IdAccount" OtherKey="Id" Type="Account" IsForeignKey="true" />
      <Association Name="FoodTable_Bill" Member="FoodTable" ThisKey="IdTable" OtherKey="IdTable" Type="FoodTable" IsForeignKey="true" />
      <Association Name="Staff_Bill" Member="Staff" ThisKey="IdStaff" OtherKey="IdStaff" Type="Staff" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DetailBill" Member="DetailBills">
    <Type Name="DetailBill">
      <Column Name="IdDetailBill" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdBill" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdFood" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Quality" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PriceDetailBill" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Bill_DetailBill" Member="Bill" ThisKey="IdBill" OtherKey="IdBill" Type="Bill" IsForeignKey="true" />
      <Association Name="Food_DetailBill" Member="Food" ThisKey="IdFood" OtherKey="IdFood" Type="Food" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Food" Member="Foods">
    <Type Name="Food">
      <Column Name="IdFood" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NameFood" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IdFC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="anh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Food_DetailBill" Member="DetailBills" ThisKey="IdFood" OtherKey="IdFood" Type="DetailBill" />
      <Association Name="FoodCategory_Food" Member="FoodCategory" ThisKey="IdFC" OtherKey="IdFC" Type="FoodCategory" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FoodCategory" Member="FoodCategories">
    <Type Name="FoodCategory">
      <Column Name="IdFC" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FoodCategory" Member="FoodCategory1" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="FoodCategory_Food" Member="Foods" ThisKey="IdFC" OtherKey="IdFC" Type="Food" />
    </Type>
  </Table>
  <Table Name="dbo.FoodTable" Member="FoodTables">
    <Type Name="FoodTable">
      <Column Name="IdTable" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="FoodTable_Bill" Member="Bills" ThisKey="IdTable" OtherKey="IdTable" Type="Bill" />
    </Type>
  </Table>
  <Table Name="dbo.Slider" Member="Sliders">
    <Type Name="Slider">
      <Column Name="maHinh" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="anh" Type="System.String" DbType="NVarChar(125) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Staff" Member="Staffs">
    <Type Name="Staff">
      <Column Name="IdStaff" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdAccount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NameStaff" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NumberPhone" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Staff_Bill" Member="Bills" ThisKey="IdStaff" OtherKey="IdStaff" Type="Bill" />
      <Association Name="Account_Staff" Member="Account" ThisKey="IdAccount" OtherKey="Id" Type="Account" IsForeignKey="true" />
    </Type>
  </Table>
</Database>